(() => {
  'use strict';
  const cfg=window.KAMBUZ_CONFIG||{}; let client=null;
  const endpoint=()=>`${String(cfg.SUPABASE_URL||'').replace(/\/$/,'')}/functions/v1/kambuz-pin-auth`;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const nameOf=u=>String(u?.user_metadata?.display_name||u?.user_metadata?.login||'').trim();
  function loadSupabase(){if(window.supabase)return Promise.resolve(window.supabase);return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>window.supabase?res(window.supabase):rej(new Error('Модуль входа не запустился'));s.onerror=()=>rej(new Error('Не удалось загрузить модуль входа'));document.head.appendChild(s)})}
  function style(){if(document.getElementById('kambuz-auth-style'))return;const s=document.createElement('style');s.id='kambuz-auth-style';s.textContent=`.kauth-overlay{position:fixed;inset:0;z-index:100000;background:#f3f7f5;display:flex;align-items:center;justify-content:center;padding:24px;font-family:system-ui;color:#18322c}.kauth-card{width:min(430px,100%);background:#fff;border-radius:24px;padding:24px;box-shadow:0 18px 60px #0f372c29}.kauth-logo{font-size:30px;font-weight:800}.kauth-sub{color:#61766f;line-height:1.4}.kauth-tabs{display:grid;grid-template-columns:1fr 1fr;background:#edf3f0;border-radius:14px;padding:4px;margin:18px 0}.kauth-tab{border:0;background:transparent;border-radius:11px;padding:10px;font-weight:700}.kauth-tab.active{background:#fff;color:#0b5d4b}.kauth-field{display:block;margin:12px 0}.kauth-field span{display:block;font-size:13px;font-weight:700;margin-bottom:6px}.kauth-field input{box-sizing:border-box;width:100%;font-size:18px;padding:13px 14px;border:1px solid #cbd8d3;border-radius:13px}.kauth-submit{width:100%;border:0;border-radius:14px;background:#0b5d4b;color:#fff;font-size:16px;font-weight:800;padding:14px}.kauth-msg{font-size:13px;margin-top:12px;color:#9b3d36}.kauth-pill{position:fixed;z-index:90000;right:12px;top:calc(env(safe-area-inset-top) + 8px);border:0;border-radius:999px;background:#fffffff0;box-shadow:0 3px 16px #0002;padding:8px 11px;font:700 12px system-ui;color:#23433a}.kauth-sheet{position:fixed;inset:0;z-index:100001;background:#0006;display:flex;align-items:flex-end}.kauth-sheet-card{width:100%;background:#fff;border-radius:22px 22px 0 0;padding:22px;padding-bottom:calc(env(safe-area-inset-bottom) + 22px);font-family:system-ui;color:#18322c}.kauth-sheet-card button{width:100%;padding:13px;border-radius:13px;border:0;margin-top:9px;font-weight:800}`;document.head.appendChild(s)}
  async function call(action,login,pin,display_name=''){const r=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.SUPABASE_ANON_KEY},body:JSON.stringify({action,login,pin,display_name})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Ошибка входа');return j}
  async function acceptSession(session){const {error}=await client.auth.setSession({access_token:session.access_token,refresh_token:session.refresh_token});if(error)throw error;const n=nameOf(session.user);if(n)localStorage.setItem('kambuz_user',n);location.reload()}
  function loginScreen(){style();document.querySelector('.kauth-overlay')?.remove();const r=document.createElement('div');r.className='kauth-overlay';r.innerHTML=`<div class="kauth-card"><div class="kauth-logo">🍽️ Камбуз</div><p class="kauth-sub">Общий склад команды. Никакой почты — только свой логин и PIN.</p><div class="kauth-tabs"><button class="kauth-tab active" data-m="login">Войти</button><button class="kauth-tab" data-m="signup">Создать</button></div><form><label class="kauth-field kauth-name" style="display:none"><span>Имя в истории</span><input name="name" placeholder="Никита"></label><label class="kauth-field"><span>Логин</span><input name="login" autocapitalize="none" autocomplete="username" required placeholder="nikita"></label><label class="kauth-field"><span>PIN</span><input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" required placeholder="4–8 цифр"></label><button class="kauth-submit">Войти в Камбуз</button><div class="kauth-msg"></div></form></div>`;document.body.appendChild(r);let mode='login';r.querySelectorAll('.kauth-tab').forEach(b=>b.onclick=()=>{mode=b.dataset.m;r.querySelectorAll('.kauth-tab').forEach(x=>x.classList.toggle('active',x===b));r.querySelector('.kauth-name').style.display=mode==='signup'?'block':'none';r.querySelector('.kauth-submit').textContent=mode==='signup'?'Создать пользователя':'Войти в Камбуз';r.querySelector('.kauth-msg').textContent=''});r.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=r.querySelector('.kauth-submit');b.disabled=true;const f=new FormData(e.currentTarget);try{const j=await call(mode,String(f.get('login')||''),String(f.get('pin')||''),String(f.get('name')||''));await acceptSession(j.session)}catch(x){r.querySelector('.kauth-msg').textContent=x.message||'Ошибка'}finally{b.disabled=false}}}
  async function account(user){style();const n=nameOf(user)||'Пользователь';localStorage.setItem('kambuz_user',n);let role='user';try{const q=await client.from('crew_members').select('role').eq('user_id',user.id).maybeSingle();role=q.data?.role||role}catch{}const p=document.createElement('button');p.className='kauth-pill';p.textContent=`👤 ${n}`;p.onclick=()=>{const s=document.createElement('div');s.className='kauth-sheet';s.innerHTML=`<div class="kauth-sheet-card"><b style="font-size:20px">${esc(n)}</b><div style="color:#61766f;margin:5px 0 12px">${role==='admin'?'Администратор':'Пользователь'}</div><button class="out" style="background:#fff0ef;color:#a33">Выйти</button><button class="close" style="background:#edf3f0">Закрыть</button></div>`;s.querySelector('.close').onclick=()=>s.remove();s.querySelector('.out').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('kambuz_user');location.reload()};s.onclick=e=>{if(e.target===s)s.remove()};document.body.appendChild(s)};document.body.appendChild(p)}
  async function start(){style();try{const lib=await loadSupabase();client=lib.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await client.auth.getSession();if(!data?.session?.user)return loginScreen();await account(data.session.user)}catch(e){loginScreen();const m=document.querySelector('.kauth-msg');if(m)m.textContent=e.message||'Ошибка входа'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();