const VERSION = '2.0.2';
const CACHE = `kambuz-shell-${VERSION}`;
const SCOPE = self.registration.scope;
const url = path => new URL(path, SCOPE).href;
const SHELL=['./','./index.html','./styles.css?v=1.2.4','./app.js?v=1.2.4','./config.js?v=1.2.4','./auth-addon.js?v=2.0.1','./merge-tombstone-addon.js?v=2.0.2','./local-ops-sanitizer.js?v=1.9.1','./classification-addon.js?v=1.8.0','./sync-resilience-addon.js?v=1.2.2','./offline-receipt-addon.js?v=1.3.1','./inventory-addon.js?v=1.4.0','./duplicate-cleanup-addon.js?v=1.5.0','./bulk-writeoff-addon.js?v=1.6.0','./imo-report-addon.js?v=1.8.0','./item-card-addon.js?v=1.9.3','./average-consumption-addon.js?v=1.9.4','./sync-queue-ui-addon.js?v=1.2.4','./version-addon.js?v=2.0.2','./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png'].map(url);
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);const results=await Promise.allSettled(SHELL.map(async resource=>{const response=await fetch(new Request(resource,{cache:'reload'}));if(!response.ok)throw new Error(`${response.status} ${resource}`);await cache.put(resource,response.clone())}));const required=SHELL.filter(x=>!/manifest|icon-/.test(x));for(const resource of required){if(!(await cache.match(resource))){const failed=results.filter(r=>r.status==='rejected').map(r=>r.reason?.message).join('; ');throw new Error(`Не удалось создать офлайн-кэш: ${resource}. ${failed}`)}}await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
async function cachedShell(path){const cache=await caches.open(CACHE);return(await cache.match(url(path)))||(await cache.match(url(path),{ignoreSearch:true}))}
async function fetchWithTimeout(request,ms=2500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(request,{cache:'no-store',signal:c.signal})}finally{clearTimeout(t)}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);if(u.origin!==self.location.origin)return;if(event.request.mode==='navigate'){event.respondWith((async()=>{const cache=await caches.open(CACHE);try{const fresh=await fetchWithTimeout(event.request);if(fresh?.ok){await cache.put(url('./index.html'),fresh.clone());return fresh}}catch{}const cached=await cachedShell('./index.html');if(cached)return cached;return new Response('<h1>Камбуз</h1><p>Один раз открой приложение с интернетом.</p>',{headers:{'Content-Type':'text/html; charset=utf-8'}})})());return}event.respondWith((async()=>{const cache=await caches.open(CACHE);const cached=(await cache.match(event.request))||(await cache.match(event.request,{ignoreSearch:true}));if(cached)return cached;try{const fresh=await fetch(event.request);if(fresh.ok)await cache.put(event.request,fresh.clone());return fresh}catch{return new Response('',{status:503})}})())});